const cfg=window.CP_SUPABASE||{};const valid=cfg.url&&cfg.anonKey&&!cfg.url.includes('TU-PROYECTO')&&!cfg.anonKey.includes('TU_');
let sb,all=[];const $=id=>document.getElementById(id);const login=$('login'),dash=$('dashboard');
if(valid) sb=window.supabase.createClient(cfg.url,cfg.anonKey); else $('loginMsg').textContent='Configura supabase-config.js con la URL y publishable/anon key del proyecto.';
async function start(){if(!sb)return;const {data:{session}}=await sb.auth.getSession();if(session) await enter(session);sb.auth.onAuthStateChange((_e,s)=>{if(s)enter(s);else showLogin()})}
function showLogin(){login.hidden=false;dash.hidden=true;$('userEmail').textContent=''}
async function enter(session){login.hidden=true;dash.hidden=false;$('userEmail').textContent=session.user.email||'';await load()}
$('loginForm').onsubmit=async e=>{e.preventDefault();if(!sb)return;const {error}=await sb.auth.signInWithPassword({email:$('email').value,password:$('password').value});$('loginMsg').textContent=error?error.message:''};$('logout').onclick=()=>sb?.auth.signOut();
async function load(){const {data,error}=await sb.from('products').select('*').order('updated_at',{ascending:false});if(error){alert(error.message);return}all=data||[];render();await loadClickStats()}
function render(){const q=$('search').value.toLowerCase(),c=$('cat').value;const ps=all.filter(p=>(!c||p.category===c)&&(!q||`${p.name} ${p.bank} ${p.category}`.toLowerCase().includes(q)));$('countAll').textContent=all.length;$('countActive').textContent=all.filter(p=>p.active).length;$('countFeatured').textContent=all.filter(p=>p.featured).length;$('tableWrap').innerHTML=`<div class="table"><div class="row head"><span>Producto</span><span>Categoría</span><span>TAE</span><span>Estado</span><span>Acciones</span></div>${ps.map(p=>`<div class="row"><div class="product"><b>${esc(p.name)}</b><small>${esc(p.bank)}</small></div><span>${esc(p.category)}</span><span>${esc(p.tae||'—')}</span><span class="badge">${p.active?'Activo':'Oculto'}</span><div class="actions"><button data-edit="${p.id}">Editar</button><button class="danger" data-del="${p.id}">Borrar</button></div></div>`).join('')||'<div class="row">Sin resultados.</div>'}</div>`;document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openForm(all.find(p=>p.id===b.dataset.edit)));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>del(b.dataset.del))}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function openForm(p){$('modal').hidden=false;$('modal').setAttribute('aria-hidden','false');$('modalTitle').textContent=p?'Editar producto':'Nuevo producto';$('pid').value=p?.id||'';$('name').value=p?.name||'';$('bank').value=p?.bank||'';$('pcat').value=p?.category||'Hipotecas';$('type').value=p?.type||'';$('tin').value=p?.tin||'';$('tae').value=p?.tae||'';$('term').value=p?.term||'';$('fee').value=p?.fee||'';$('min').value=p?.amount_min??'';$('max').value=p?.amount_max??'';$('highlight').value=p?.highlight||'';$('requirements').value=p?.requirements||'';$('url').value=p?.url||'';$('affiliate').value=p?.affiliate_url||'';$('network').value=p?.affiliate_network||'';$('commissionModel').value=p?.commission_model||'';$('commissionValue').value=p?.commission_value??'';$('priority').value=p?.commercial_priority??0;$('sponsored').checked=p?.sponsored??false;$('source').value=p?.source||'';$('verified').value=p?.verified_at||'';$('active').checked=p?.active??true;$('featured').checked=p?.featured??false}
function closeModal(){const m=$('modal');m.hidden=true;m.setAttribute('aria-hidden','true');$('formMsg').textContent=''}$('newBtn').onclick=()=>openForm();$('close').addEventListener('click',closeModal);$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('modal').hidden)closeModal()});$('search').oninput=render;$('cat').onchange=render;
$('productForm').onsubmit=async e=>{e.preventDefault();const p={slug:($('name').value+'-'+$('bank').value).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),name:$('name').value,bank:$('bank').value,category:$('pcat').value,type:$('type').value,tin:$('tin').value,tae:$('tae').value,term:$('term').value,fee:$('fee').value,amount_min:$('min').value?Number($('min').value):null,amount_max:$('max').value?Number($('max').value):null,highlight:$('highlight').value,requirements:$('requirements').value,url:$('url').value,affiliate_url:$('affiliate').value||null,affiliate_network:$('network').value||null,commission_model:$('commissionModel').value||null,commission_value:$('commissionValue').value?Number($('commissionValue').value):null,commercial_priority:$('priority').value?Number($('priority').value):0,sponsored:$('sponsored').checked,source:$('source').value,verified_at:$('verified').value||null,active:$('active').checked,featured:$('featured').checked,updated_at:new Date().toISOString()};const id=$('pid').value;const q=id?sb.from('products').update(p).eq('id',id):sb.from('products').insert(p);const {error}=await q;if(error){$('formMsg').textContent=error.message;return}closeModal();await load()};
async function del(id){if(!confirm('¿Borrar este producto?'))return;const {error}=await sb.from('products').delete().eq('id',id);if(error)alert(error.message);else load()}async function loadClickStats(){
  const out=$('statsOutput'); if(!out||!sb)return;
  const {data,error}=await sb.from('product_clicks').select('product_id,event_type,created_at').order('created_at',{ascending:false}).limit(5000);
  if(error){out.textContent='No disponible: '+error.message;return}
  const counts={affiliate_click:0,official_click:0};(data||[]).forEach(x=>counts[x.event_type]=(counts[x.event_type]||0)+1);
  out.innerHTML='<b>'+counts.affiliate_click+' clics de afiliación</b> · '+(counts.official_click||0)+' clics oficiales · '+((data||[]).length)+' clics registrados';
}
$('refreshStats')?.addEventListener('click',loadClickStats);
start();
